!coverage.py: This is a private format, don't read it directly!{"lines":{"/app/service/__init__.py":[1,7,8,9,10,13,14,17,20,21,22,23,24,26,27,29,31,33,34,35,37,38,44],"/app/service/routes.py":[1,7,8,9,10,11,12,13,14,19,20,23,28,29,41,42,63,64,74,75,90,91,105,106,120,131,133,76,77,122,123,124,78,79,80,81,82,84,85,86,65,66,67,70,71,125,126,127,128,107,108,109,110,112,113,68,44,45,46,47,48,49,51,53,56,58,59,60,31,33,34,35,36,38,32,50,92,93,94,95,97,98,99,101,102],"/app/service/status.py":[15,23,24,27,28,29,30,31,32,33,36,37,38,39,40,41,42,43,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,69,70,71,72,73,74,75],"/app/service/models.py":[1,6,7,9,12,15,18,19,21,24,25,29,32,33,34,35,37,46,55,61,69,88,89,100,101,105,106,110,111,115,116,120,121,125,126,131,132,94,96,97,98,102,103,41,42,43,44,57,58,59,75,76,77,86,78,80,82,83,84,81,133,134,117,118,112,113,127,128,64,65,66,63,50,51,53,107,108],"/app/service/error_handlers.py":[14,17,18,19,24,25,30,31,43,44,69,70,84,85,72,73,75,76,77,78,80,74,27,33,34,36,37,39,35,46,47,49,50,48]}}